/**
 * Stable, machine-readable error codes.
 *
 * The web client switches on `error.code`, never on `error.message`, so messages
 * can be reworded or localised without breaking behaviour.
 */
export const ERROR_CODES = {
  // generic
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMITED: 'RATE_LIMITED',

  // auth
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  DUPLICATE_ACCOUNT_SUSPECTED: 'DUPLICATE_ACCOUNT_SUSPECTED',

  // participation
  VOTE_DUPLICATE: 'VOTE_DUPLICATE',
  VOTE_LIMIT_REACHED: 'VOTE_LIMIT_REACHED',
  SELF_VOTE_FORBIDDEN: 'SELF_VOTE_FORBIDDEN',
  POLL_CLOSED: 'POLL_CLOSED',
  POLL_NOT_ACTIVE: 'POLL_NOT_ACTIVE',
  PREDICTION_CLOSED: 'PREDICTION_CLOSED',
  PREDICTION_ALREADY_SUBMITTED: 'PREDICTION_ALREADY_SUBMITTED',
  ROUND_CLOSED: 'ROUND_CLOSED',
  OPTION_INVALID: 'OPTION_INVALID',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
  SUBMISSION_CLOSED: 'SUBMISSION_CLOSED',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  CONTENT_REJECTED: 'CONTENT_REJECTED',

  // economy
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
  REWARD_UNAVAILABLE: 'REWARD_UNAVAILABLE',
  ALREADY_CLAIMED: 'ALREADY_CLAIMED',

  // lifecycle
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorBody {
  error: {
    code: ErrorCode | string;
    message: string;
    details?: unknown;
    requestId?: string;
  };
}
